In [1]:
import pandas as pd

In [2]:
m2or = pd.read_csv("../../../Data/m2or_pairs.csv", sep=";")
m2or

,Species,Gene Name,UniProt ID,Mutation,Sequence,Molecule Name,CID,CAS,InChIKey,SMILES,Mixture,Responsive,Data Quality,Number of Unique Value Screen
0,homo sapiens,OR10S1,Q8NGN2,NaN,MTSRSVCEKMTMTTENPNQTVVSHFFLEGLRYTAKHSSLFFLLFLL...,(-)-limonene,439250.0,5989-54-8,XMGQYMWWDOXHJM-SNVBAGLBSA-N,CC1=CC[C@H](CC1)C(=C)C,mono,0,primaryScreening,1.0
1,homo sapiens,OR10S1,Q8NGN2,NaN,MTSRSVCEKMTMTTENPNQTVVSHFFLEGLRYTAKHSSLFFLLFLL...,(+)-carvone,16724.0,6485-40-1,ULDHMXUKGWMISQ-VIFPVBQESA-N,CC1=CC[C@@H](CC1=O)C(=C)C,mono,0,secondaryScreening,2.0
2,homo sapiens,OR10S1,Q8NGN2,NaN,MTSRSVCEKMTMTTENPNQTVVSHFFLEGLRYTAKHSSLFFLLFLL...,(+)-menthol,165675.0,2216-51-5,NOOLISFMXDJSKH-AEJSXWLSSA-N,C[C@H]1CC[C@@H]([C@H](C1)O)C(C)C,mono,0,primaryScreening,1.0
3,homo sapiens,OR10S1,Q8NGN2,NaN,MTSRSVCEKMTMTTENPNQTVVSHFFLEGLRYTAKHSSLFFLLFLL...,1-butanol,263.0,71-36-3,LRHPLDYGYMQRHN-UHFFFAOYSA-N,CCCCO,mono,0,primaryScreening,1.0
4,homo sapiens,OR10S1,Q8NGN2,NaN,MTSRSVCEKMTMTTENPNQTVVSHFFLEGLRYTAKHSSLFFLLFLL...,1-butoxy-2-propanol,21210.0,5131-66-8,RWNUSVWFHDHRCJ-UHFFFAOYSA-N,CCCCOCC(C)O,sum of isomers,0,primaryScreening,1.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
53439,homo sapiens,OR51F1_OR51F1P,A6NGY5,NaN,MLQNQDTMEILSNSTSKFPTFLLTGIPGLESAHVWISIPFCCFYAI...,N-hexanal,6184.0,66-25-1,JARKCYVAAOWBJS-UHFFFAOYSA-N,CCCCCC=O,mono,0,primaryScreening,1.0
53440,homo sapiens,OR51T1,Q8NGJ9,NaN,MAIFNNTTSSSSNFLLTAFPGLECAHVWISIPVCCLYTIALLGNSM...,N-hexanal,6184.0,66-25-1,JARKCYVAAOWBJS-UHFFFAOYSA-N,CCCCCC=O,mono,0,primaryScreening,1.0
53441,homo sapiens,OR52E5,Q8NH55,NaN,MLHTNNTQFHPSTFLVVGVPGLEDVHVWIGFPFFAVYLTALLGNII...,N-hexanal,6184.0,66-25-1,JARKCYVAAOWBJS-UHFFFAOYSA-N,CCCCCC=O,mono,0,primaryScreening,1.0
53442,homo sapiens,OR52L1,Q8NGH7,NaN,MTLVSFFSFLSKPLIMLLSNSSWRLSQPSFLLVGIPGLEESQHWIA...,N-hexanal,6184.0,66-25-1,JARKCYVAAOWBJS-UHFFFAOYSA-N,CCCCCC=O,mono,0,primaryScreening,1.0
53443,homo sapiens,OR56A4,Q8NGH8,NaN,MASPSNDSTAPVSEFLLICFPNFQSWQHWLSLPLSLLFLLAMGANT...,N-hexanal,6184.0,66-25-1,JARKCYVAAOWBJS-UHFFFAOYSA-N,CCCCCC=O,mono,0,primaryScreening,1.0

### create unique identifiers for proteins & ligands

In [3]:
seq_codes, seq_uniques = pd.factorize(m2or['Sequence'])
smiles_codes, smiles_uniques = pd.factorize(m2or['SMILES'])

m2or['seq_id'] = [f'SEQ{code:04d}' for code in seq_codes]
m2or['smiles_id'] = [f'SML{code:04d}' for code in smiles_codes]

seq_mapping = pd.DataFrame({'seq_id': [f'SEQ{idx:04d}' for idx in range(len(seq_uniques))],
                           'Sequence': seq_uniques})

smiles_mapping = pd.DataFrame({'smiles_id': [f'SML{idx:04d}' for idx in range(len(smiles_uniques))],
                              'SMILES': smiles_uniques})

In [4]:
m2or

,Species,Gene Name,UniProt ID,Mutation,Sequence,Molecule Name,CID,CAS,InChIKey,SMILES,Mixture,Responsive,Data Quality,Number of Unique Value Screen,seq_id,smiles_id
0,homo sapiens,OR10S1,Q8NGN2,NaN,MTSRSVCEKMTMTTENPNQTVVSHFFLEGLRYTAKHSSLFFLLFLL...,(-)-limonene,439250.0,5989-54-8,XMGQYMWWDOXHJM-SNVBAGLBSA-N,CC1=CC[C@H](CC1)C(=C)C,mono,0,primaryScreening,1.0,SEQ0000,SML0000
1,homo sapiens,OR10S1,Q8NGN2,NaN,MTSRSVCEKMTMTTENPNQTVVSHFFLEGLRYTAKHSSLFFLLFLL...,(+)-carvone,16724.0,6485-40-1,ULDHMXUKGWMISQ-VIFPVBQESA-N,CC1=CC[C@@H](CC1=O)C(=C)C,mono,0,secondaryScreening,2.0,SEQ0000,SML0001
2,homo sapiens,OR10S1,Q8NGN2,NaN,MTSRSVCEKMTMTTENPNQTVVSHFFLEGLRYTAKHSSLFFLLFLL...,(+)-menthol,165675.0,2216-51-5,NOOLISFMXDJSKH-AEJSXWLSSA-N,C[C@H]1CC[C@@H]([C@H](C1)O)C(C)C,mono,0,primaryScreening,1.0,SEQ0000,SML0002
3,homo sapiens,OR10S1,Q8NGN2,NaN,MTSRSVCEKMTMTTENPNQTVVSHFFLEGLRYTAKHSSLFFLLFLL...,1-butanol,263.0,71-36-3,LRHPLDYGYMQRHN-UHFFFAOYSA-N,CCCCO,mono,0,primaryScreening,1.0,SEQ0000,SML0003
4,homo sapiens,OR10S1,Q8NGN2,NaN,MTSRSVCEKMTMTTENPNQTVVSHFFLEGLRYTAKHSSLFFLLFLL...,1-butoxy-2-propanol,21210.0,5131-66-8,RWNUSVWFHDHRCJ-UHFFFAOYSA-N,CCCCOCC(C)O,sum of isomers,0,primaryScreening,1.0,SEQ0000,SML0004
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
53439,homo sapiens,OR51F1_OR51F1P,A6NGY5,NaN,MLQNQDTMEILSNSTSKFPTFLLTGIPGLESAHVWISIPFCCFYAI...,N-hexanal,6184.0,66-25-1,JARKCYVAAOWBJS-UHFFFAOYSA-N,CCCCCC=O,mono,0,primaryScreening,1.0,SEQ0523,SML0163
53440,homo sapiens,OR51T1,Q8NGJ9,NaN,MAIFNNTTSSSSNFLLTAFPGLECAHVWISIPVCCLYTIALLGNSM...,N-hexanal,6184.0,66-25-1,JARKCYVAAOWBJS-UHFFFAOYSA-N,CCCCCC=O,mono,0,primaryScreening,1.0,SEQ0952,SML0163
53441,homo sapiens,OR52E5,Q8NH55,NaN,MLHTNNTQFHPSTFLVVGVPGLEDVHVWIGFPFFAVYLTALLGNII...,N-hexanal,6184.0,66-25-1,JARKCYVAAOWBJS-UHFFFAOYSA-N,CCCCCC=O,mono,0,primaryScreening,1.0,SEQ0955,SML0163
53442,homo sapiens,OR52L1,Q8NGH7,NaN,MTLVSFFSFLSKPLIMLLSNSSWRLSQPSFLLVGIPGLEESQHWIA...,N-hexanal,6184.0,66-25-1,JARKCYVAAOWBJS-UHFFFAOYSA-N,CCCCCC=O,mono,0,primaryScreening,1.0,SEQ0957,SML0163
53443,homo sapiens,OR56A4,Q8NGH8,NaN,MASPSNDSTAPVSEFLLICFPNFQSWQHWLSLPLSLLFLLAMGANT...,N-hexanal,6184.0,66-25-1,JARKCYVAAOWBJS-UHFFFAOYSA-N,CCCCCC=O,mono,0,primaryScreening,1.0,SEQ0506,SML0163

In [5]:
m2or["seq_id"].nunique()

1402

In [6]:
m2or["SMILES"].nunique()

771

### remove mixture compounds

In [7]:
pairs = m2or[m2or["Mixture"] != "mixture"]

In [8]:
pairs

,Species,Gene Name,UniProt ID,Mutation,Sequence,Molecule Name,CID,CAS,InChIKey,SMILES,Mixture,Responsive,Data Quality,Number of Unique Value Screen,seq_id,smiles_id
0,homo sapiens,OR10S1,Q8NGN2,NaN,MTSRSVCEKMTMTTENPNQTVVSHFFLEGLRYTAKHSSLFFLLFLL...,(-)-limonene,439250.0,5989-54-8,XMGQYMWWDOXHJM-SNVBAGLBSA-N,CC1=CC[C@H](CC1)C(=C)C,mono,0,primaryScreening,1.0,SEQ0000,SML0000
1,homo sapiens,OR10S1,Q8NGN2,NaN,MTSRSVCEKMTMTTENPNQTVVSHFFLEGLRYTAKHSSLFFLLFLL...,(+)-carvone,16724.0,6485-40-1,ULDHMXUKGWMISQ-VIFPVBQESA-N,CC1=CC[C@@H](CC1=O)C(=C)C,mono,0,secondaryScreening,2.0,SEQ0000,SML0001
2,homo sapiens,OR10S1,Q8NGN2,NaN,MTSRSVCEKMTMTTENPNQTVVSHFFLEGLRYTAKHSSLFFLLFLL...,(+)-menthol,165675.0,2216-51-5,NOOLISFMXDJSKH-AEJSXWLSSA-N,C[C@H]1CC[C@@H]([C@H](C1)O)C(C)C,mono,0,primaryScreening,1.0,SEQ0000,SML0002
3,homo sapiens,OR10S1,Q8NGN2,NaN,MTSRSVCEKMTMTTENPNQTVVSHFFLEGLRYTAKHSSLFFLLFLL...,1-butanol,263.0,71-36-3,LRHPLDYGYMQRHN-UHFFFAOYSA-N,CCCCO,mono,0,primaryScreening,1.0,SEQ0000,SML0003
4,homo sapiens,OR10S1,Q8NGN2,NaN,MTSRSVCEKMTMTTENPNQTVVSHFFLEGLRYTAKHSSLFFLLFLL...,1-butoxy-2-propanol,21210.0,5131-66-8,RWNUSVWFHDHRCJ-UHFFFAOYSA-N,CCCCOCC(C)O,sum of isomers,0,primaryScreening,1.0,SEQ0000,SML0004
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
53439,homo sapiens,OR51F1_OR51F1P,A6NGY5,NaN,MLQNQDTMEILSNSTSKFPTFLLTGIPGLESAHVWISIPFCCFYAI...,N-hexanal,6184.0,66-25-1,JARKCYVAAOWBJS-UHFFFAOYSA-N,CCCCCC=O,mono,0,primaryScreening,1.0,SEQ0523,SML0163
53440,homo sapiens,OR51T1,Q8NGJ9,NaN,MAIFNNTTSSSSNFLLTAFPGLECAHVWISIPVCCLYTIALLGNSM...,N-hexanal,6184.0,66-25-1,JARKCYVAAOWBJS-UHFFFAOYSA-N,CCCCCC=O,mono,0,primaryScreening,1.0,SEQ0952,SML0163
53441,homo sapiens,OR52E5,Q8NH55,NaN,MLHTNNTQFHPSTFLVVGVPGLEDVHVWIGFPFFAVYLTALLGNII...,N-hexanal,6184.0,66-25-1,JARKCYVAAOWBJS-UHFFFAOYSA-N,CCCCCC=O,mono,0,primaryScreening,1.0,SEQ0955,SML0163
53442,homo sapiens,OR52L1,Q8NGH7,NaN,MTLVSFFSFLSKPLIMLLSNSSWRLSQPSFLLVGIPGLEESQHWIA...,N-hexanal,6184.0,66-25-1,JARKCYVAAOWBJS-UHFFFAOYSA-N,CCCCCC=O,mono,0,primaryScreening,1.0,SEQ0957,SML0163
53443,homo sapiens,OR56A4,Q8NGH8,NaN,MASPSNDSTAPVSEFLLICFPNFQSWQHWLSLPLSLLFLLAMGANT...,N-hexanal,6184.0,66-25-1,JARKCYVAAOWBJS-UHFFFAOYSA-N,CCCCCC=O,mono,0,primaryScreening,1.0,SEQ0506,SML0163

In [9]:
pairs["seq_id"].nunique()

1399

In [10]:
pairs["SMILES"].nunique()

754

In [10]:
pairs = pairs.drop(columns=["Gene Name", "Molecule Name", "CID", "CAS", "InChIKey", "Data Quality", "Number of Unique Value Screen"])
pairs

,Species,UniProt ID,Mutation,Sequence,SMILES,Mixture,Responsive,seq_id,smiles_id
0,homo sapiens,Q8NGN2,NaN,MTSRSVCEKMTMTTENPNQTVVSHFFLEGLRYTAKHSSLFFLLFLL...,CC1=CC[C@H](CC1)C(=C)C,mono,0,SEQ0000,SML0000
1,homo sapiens,Q8NGN2,NaN,MTSRSVCEKMTMTTENPNQTVVSHFFLEGLRYTAKHSSLFFLLFLL...,CC1=CC[C@@H](CC1=O)C(=C)C,mono,0,SEQ0000,SML0001
2,homo sapiens,Q8NGN2,NaN,MTSRSVCEKMTMTTENPNQTVVSHFFLEGLRYTAKHSSLFFLLFLL...,C[C@H]1CC[C@@H]([C@H](C1)O)C(C)C,mono,0,SEQ0000,SML0002
3,homo sapiens,Q8NGN2,NaN,MTSRSVCEKMTMTTENPNQTVVSHFFLEGLRYTAKHSSLFFLLFLL...,CCCCO,mono,0,SEQ0000,SML0003
4,homo sapiens,Q8NGN2,NaN,MTSRSVCEKMTMTTENPNQTVVSHFFLEGLRYTAKHSSLFFLLFLL...,CCCCOCC(C)O,sum of isomers,0,SEQ0000,SML0004
...,...,...,...,...,...,...,...,...,...
53439,homo sapiens,A6NGY5,NaN,MLQNQDTMEILSNSTSKFPTFLLTGIPGLESAHVWISIPFCCFYAI...,CCCCCC=O,mono,0,SEQ0523,SML0163
53440,homo sapiens,Q8NGJ9,NaN,MAIFNNTTSSSSNFLLTAFPGLECAHVWISIPVCCLYTIALLGNSM...,CCCCCC=O,mono,0,SEQ0952,SML0163
53441,homo sapiens,Q8NH55,NaN,MLHTNNTQFHPSTFLVVGVPGLEDVHVWIGFPFFAVYLTALLGNII...,CCCCCC=O,mono,0,SEQ0955,SML0163
53442,homo sapiens,Q8NGH7,NaN,MTLVSFFSFLSKPLIMLLSNSSWRLSQPSFLLVGIPGLEESQHWIA...,CCCCCC=O,mono,0,SEQ0957,SML0163
53443,homo sapiens,Q8NGH8,NaN,MASPSNDSTAPVSEFLLICFPNFQSWQHWLSLPLSLLFLLAMGANT...,CCCCCC=O,mono,0,SEQ0506,SML0163

### create boolean column for Mutation

In [11]:
# add a new boolean column "mutation", having True if "Mutation" is not null
pairs['mutation'] = pairs['Mutation'].notnull()

In [12]:
pairs.drop(columns=["Mutation"], inplace=True)

In [13]:
pairs

,Species,UniProt ID,Sequence,SMILES,Mixture,Responsive,seq_id,smiles_id,mutation
0,homo sapiens,Q8NGN2,MTSRSVCEKMTMTTENPNQTVVSHFFLEGLRYTAKHSSLFFLLFLL...,CC1=CC[C@H](CC1)C(=C)C,mono,0,SEQ0000,SML0000,False
1,homo sapiens,Q8NGN2,MTSRSVCEKMTMTTENPNQTVVSHFFLEGLRYTAKHSSLFFLLFLL...,CC1=CC[C@@H](CC1=O)C(=C)C,mono,0,SEQ0000,SML0001,False
2,homo sapiens,Q8NGN2,MTSRSVCEKMTMTTENPNQTVVSHFFLEGLRYTAKHSSLFFLLFLL...,C[C@H]1CC[C@@H]([C@H](C1)O)C(C)C,mono,0,SEQ0000,SML0002,False
3,homo sapiens,Q8NGN2,MTSRSVCEKMTMTTENPNQTVVSHFFLEGLRYTAKHSSLFFLLFLL...,CCCCO,mono,0,SEQ0000,SML0003,False
4,homo sapiens,Q8NGN2,MTSRSVCEKMTMTTENPNQTVVSHFFLEGLRYTAKHSSLFFLLFLL...,CCCCOCC(C)O,sum of isomers,0,SEQ0000,SML0004,False
...,...,...,...,...,...,...,...,...,...
53439,homo sapiens,A6NGY5,MLQNQDTMEILSNSTSKFPTFLLTGIPGLESAHVWISIPFCCFYAI...,CCCCCC=O,mono,0,SEQ0523,SML0163,False
53440,homo sapiens,Q8NGJ9,MAIFNNTTSSSSNFLLTAFPGLECAHVWISIPVCCLYTIALLGNSM...,CCCCCC=O,mono,0,SEQ0952,SML0163,False
53441,homo sapiens,Q8NH55,MLHTNNTQFHPSTFLVVGVPGLEDVHVWIGFPFFAVYLTALLGNII...,CCCCCC=O,mono,0,SEQ0955,SML0163,False
53442,homo sapiens,Q8NGH7,MTLVSFFSFLSKPLIMLLSNSSWRLSQPSFLLVGIPGLEESQHWIA...,CCCCCC=O,mono,0,SEQ0957,SML0163,False
53443,homo sapiens,Q8NGH8,MASPSNDSTAPVSEFLLICFPNFQSWQHWLSLPLSLLFLLAMGANT...,CCCCCC=O,mono,0,SEQ0506,SML0163,False

### create class 1/class 2 based on phylogeny

In [14]:
unique_sequences = pairs[['seq_id', 'Sequence']].drop_duplicates().set_index('seq_id')
with open('../processed/m2or_sequences_phylogeny.fasta', 'w') as f:
    for seq_id, sequence in unique_sequences.itertuples(index=True):
        f.write(f'>{seq_id}\n{sequence}\n')

In [15]:
!grep -c '>' ../processed/m2or_sequences_phylogeny.fasta

1399

In [17]:
# run mafft with einsi

!einsi --auto ../processed/m2or_sequences_phylogeny.fasta > ../processed/m2or_sequences_phylogeny_msa.fasta

nthread = 0
nthreadpair = 0
nthreadtb = 0
ppenalty_ex = 0
stacksize: 8192 kb
rescale = 1
Gap Penalty = -1.53, +0.00, +0.00



Making a distance matrix ..
 1301 / 1399
done.

Constructing a UPGMA tree (efffree=0) ...
 1390 / 1399
done.

Progressive alignment 1/2...
STEP  1101 / 1398  h
Reallocating..done. *alloclen = 1742
STEP  1301 / 1398  h
done.

Making a distance matrix from msa..
 1300 / 1399
done.

Constructing a UPGMA tree (efffree=1) ...
 1390 / 1399
done.

Progressive alignment 2/2...
STEP  1101 / 1398  h
Reallocating..done. *alloclen = 1742
STEP  1301 / 1398  h
done.

disttbfast (aa) Version 7.505
alg=A, model=BLOSUM62, 1.53, -0.00, -0.00, noshift, amax=0.0
0 thread(s)


Strategy:
 NW-NS-2 (Fast but rough)
 Progressive method (guide trees were built 2 times.)

If unsure which option to use, try 'mafft --auto input > output'.
For more information, see 'mafft --help', 'mafft --man' and the mafft page.

The default gap scoring scheme has been changed in version 7.110 (2013 Oct).
It tends to insert more gaps into gap-rich regions than previous versions.
To disable this change, add the --leavegappyregion option.

In [21]:
# run trimal with gt 0.1
!trimal -in ../processed/m2or_sequences_phylogeny_msa.fasta -out ../processed/m2or_sequences_phylogeny_msa_gt01.fasta -gt 0.1

In [22]:
# run iqtree maximum likelihood with 1000 bootstraps

!iqtree -s ../processed/m2or_sequences_phylogeny_msa_gt01.fasta -m MFP -B 1000 -T 16 -pre ../processed/m2or_sequences_phylogeny_msa_gt01_iqtree.nw

IQ-TREE version 3.0.1 for Linux x86 64-bit built Jul  9 2025
Developed by Bui Quang Minh, Thomas Wong, Nhan Ly-Trong, Huaiyan Ren
Contributed by Lam-Tung Nguyen, Dominik Schrempf, Chris Bielow,
Olga Chernomor, Michael Woodhams, Diep Thi Hoang, Heiko Schmidt

Host:    nada-P8 (AVX512, FMA3, 125 GB RAM)
Command: iqtree -s ../processed/m2or_sequences_phylogeny_msa_gt01.fasta -m MFP -B 1000 -T 16 -pre ../processed/m2or_sequences_phylogeny_msa_gt01_iqtree.nw
Seed:    985843 (Using SPRNG - Scalable Parallel Random Number Generator)
Time:    Thu Mar  5 13:37:01 2026
Kernel:  AVX+FMA - 16 threads (64 CPU cores detected)

Reading alignment file ../processed/m2or_sequences_phylogeny_msa_gt01.fasta ... Fasta format detected
Reading fasta file: done in 0.00440671 secs using 46.16% CPU
Alignment most likely contains protein sequences
Constructing alignment: done in 0.00355235 secs using 1363% CPU
Alignment has 1399 sequences with 338 columns, 338 distinct patterns
338 parsimony-informative, 0 singleton sites, 0 constant sites
         Gap/Ambiguity  Composition  p-value
Analyzing sequences: done in 8.45576e-05 secs using 3350% CPU
   1  SEQ0000    7.69%    passed     37.81%
   2  SEQ0001    8.88%    passed     58.40%
   3  SEQ0002    7.99%    passed     76.50%
   4  SEQ0003    8.28%    passed     55.43%
   5  SEQ0004    8.28%    passed     95.84%
   6  SEQ0005    7.99%    passed     98.08%
   7  SEQ0006    5.92%    passed     86.68%
   8  SEQ0007    7.10%    passed     31.05%
   9  SEQ0008    7.99%    passed     74.82%
  10  SEQ0009    7.99%    passed     62.83%
  11  SEQ0010    8.28%    passed     68.05%
  12  SEQ0011    7.40%    passed     90.72%
  13  SEQ0012    5.33%    passed     99.71%
  14  SEQ0013    8.88%    passed     65.21%
  15  SEQ0014    7.99%    passed     52.50%
  16  SEQ0015    7.99%    passed     93.53%
  17  SEQ0016   13.31%    passed     86.08%
  18  SEQ0017    9.17%    passed     89.94%
  19  SEQ0018    5.62%    passed     61.55%
  20  SEQ0019   32.25%    passed     46.49%
  21  SEQ0020    8.28%    passed     95.62%
  22  SEQ0021    7.40%    passed     69.65%
  23  SEQ0022    6.80%    passed     73.04%
  24  SEQ0023   10.65%    passed     63.85%
  25  SEQ0024    8.58%    passed     69.85%
  26  SEQ0025    4.14%    passed     14.94%
  27  SEQ0026    7.99%    passed     97.76%
  28  SEQ0027    8.88%    passed     84.94%
  29  SEQ0028    8.58%    passed     99.91%
  30  SEQ0029    7.69%    passed     67.75%
  31  SEQ0030    5.92%    passed     63.57%
  32  SEQ0031    7.69%    passed     76.20%
  33  SEQ0032    7.10%    passed     61.54%
  34  SEQ0033    7.10%    passed     62.79%
  35  SEQ0034    6.51%    passed     60.40%
  36  SEQ0035    7.99%    passed     95.27%
  37  SEQ0036    7.69%    passed     24.08%
  38  SEQ0037    6.80%    passed     99.60%
  39  SEQ0038    7.99%    passed     99.14%
  40  SEQ0039    7.69%    passed     94.16%
  41  SEQ0040    5.92%    passed     88.05%
  42  SEQ0041    8.88%    passed     72.79%
  43  SEQ0042    6.80%    passed     94.49%
  44  SEQ0043   13.91%    passed     72.92%
  45  SEQ0044    8.58%    passed     96.97%
  46  SEQ0045    7.69%    passed     31.54%
  47  SEQ0046    7.10%    passed     75.44%
  48  SEQ0047    7.40%    passed     94.56%
  49  SEQ0048    7.69%    passed     47.85%
  50  SEQ0049    6.51%    passed     32.29%
  51  SEQ0050    6.80%    passed     58.35%
  52  SEQ0051    6.51%    passed     57.82%
  53  SEQ0052    7.99%    passed     46.97%
  54  SEQ0053    9.17%    passed     85.95%
  55  SEQ0054    7.10%    passed     99.29%
  56  SEQ0055    7.10%    passed     46.47%
  57  SEQ0056    7.69%    passed     96.54%
  58  SEQ0057    9.76%    passed     99.88%
  59  SEQ0058    8.58%    passed     71.62%
  60  SEQ0059    8.28%    passed     93.55%
  61  SEQ0060    8.28%    passed     54.94%
  62  SEQ0061    5.03%    passed     93.09%
  63  SEQ0062    8.88%    passed     96.69%
  64  SEQ0063    7.40%    passed     63.34%
  65  SEQ0064    6.51%    passed     76.83%
  66  SEQ0065    8.28%    passed     84.75%
  67  SEQ0066    8.28%    passed     96.83%
  68  SEQ0067    6.51%    passed     87.98%
  69  SEQ0068    8.88%    passed     69.48%
  70  SEQ0069    6.80%    failed      0.00%
  71  SEQ0070    6.21%    passed     87.68%
  72  SEQ0071    8.28%    passed     92.89%
  73  SEQ0072    8.28%    passed     83.60%
  74  SEQ0073    8.28%    passed     90.98%
  75  SEQ0074    9.76%    passed     96.30%
  76  SEQ0075    8.28%    passed     22.54%
  77  SEQ0076    8.28%    passed     90.66%
  78  SEQ0077    8.28%    passed     78.98%
  79  SEQ0078    7.10%    passed     73.03%
  80  SEQ0079    8.58%    passed     97.08%
  81  SEQ0080   10.06%    passed     74.60%
  82  SEQ0081    7.10%    passed     56.95%
  83  SEQ0082    7.10%    passed     99.00%
  84  SEQ0083    9.76%    passed     52.65%
  85  SEQ0084    6.80%    passed     15.72%
  86  SEQ0085    8.88%    passed     73.48%
  87  SEQ0086    7.10%    passed     72.95%
  88  SEQ0087    7.99%    passed     71.52%
  89  SEQ0088    6.51%    failed      0.59%
  90  SEQ0089    9.47%    failed      0.12%
  91  SEQ0090   10.65%    passed     18.20%
  92  SEQ0091    7.99%    passed     73.80%
  93  SEQ0092    5.92%    passed     87.09%
  94  SEQ0093    6.80%    passed     99.51%
  95  SEQ0094    7.69%    passed     27.50%
  96  SEQ0095    5.33%    passed     19.56%
  97  SEQ0096    6.80%    passed     98.92%
  98  SEQ0097    5.33%    passed     92.84%
  99  SEQ0098    6.80%    passed     84.63%
 100  SEQ0099    6.21%    passed     91.23%
 101  SEQ0100    8.28%    passed     98.31%
 102  SEQ0101    9.17%    passed     98.73%
 103  SEQ0102    5.92%    passed     95.54%
 104  SEQ0103    7.69%    passed     64.15%
 105  SEQ0104    6.21%    passed     63.18%
 106  SEQ0105    6.80%    passed     79.68%
 107  SEQ0106    6.80%    passed     90.37%
 108  SEQ0107    7.10%    passed     78.01%
 109  SEQ0108    8.88%    passed     68.22%
 110  SEQ0109    8.88%    passed     83.06%
 111  SEQ0110    8.58%    passed     97.78%
 112  SEQ0111    5.92%    passed     43.41%
 113  SEQ0112    7.10%    passed     55.90%
 114  SEQ0113    7.10%    passed     22.89%
 115  SEQ0114    7.10%    passed     78.37%
 116  SEQ0115    6.80%    passed     68.86%
 117  SEQ0116    9.17%    passed     86.39%
 118  SEQ0117    5.33%    passed      9.65%
 119  SEQ0118    7.99%    passed     43.15%
 120  SEQ0119    7.10%    passed     45.62%
 121  SEQ0120    8.58%    passed     60.06%
 122  SEQ0121    9.76%    passed     89.64%
 123  SEQ0122    6.21%    passed     96.62%
 124  SEQ0123    7.10%    passed     37.70%
 125  SEQ0124    6.21%    failed      0.99%
 126  SEQ0125    5.62%    passed     71.52%
 127  SEQ0126    7.40%    passed     95.76%
 128  SEQ0127    7.69%    passed     45.86%
 129  SEQ0128    6.51%    passed     43.18%
 130  SEQ0129    9.47%    passed     72.07%
 131  SEQ0130    7.69%    passed     54.16%
 132  SEQ0131    7.10%    passed     72.22%
 133  SEQ0132    7.69%    passed     92.08%
 134  SEQ0133   10.65%    passed     84.95%
 135  SEQ0134    7.40%    passed     98.22%
 136  SEQ0135    7.99%    passed     82.40%
 137  SEQ0136    8.58%    passed     72.98%
 138  SEQ0137    7.10%    passed     71.77%
 139  SEQ0138    7.99%    passed     63.12%
 140  SEQ0139    8.28%    passed     42.62%
 141  SEQ0140    9.76%    passed     14.94%
 142  SEQ0141    8.28%    passed     98.58%
 143  SEQ0142    7.99%    passed     90.35%
 144  SEQ0143    7.10%    passed     95.61%
 145  SEQ0144    8.88%    passed     76.00%
 146  SEQ0145    7.40%    passed     50.38%
 147  SEQ0146    5.03%    passed     85.36%
 148  SEQ0147    7.40%    passed     93.33%
 149  SEQ0148   10.95%    passed     90.62%
 150  SEQ0149    5.92%    passed     76.79%
 151  SEQ0150    7.10%    passed     91.98%
 152  SEQ0151    6.51%    passed     49.27%
 153  SEQ0152    8.88%    passed     95.59%
 154  SEQ0153    6.21%    passed     64.30%
 155  SEQ0154    5.33%    passed     86.27%
 156  SEQ0155    7.99%    passed     72.75%
 157  SEQ0156   10.65%    passed     63.59%
 158  SEQ0157    7.99%    passed     94.56%
 159  SEQ0158    8.88%    passed     81.10%
 160  SEQ0159    5.33%    passed     98.05%
 161  SEQ0160    8.28%    passed     56.76%
 162  SEQ0161    7.69%    passed     96.51%
 163  SEQ0162    7.40%    passed     31.13%
 164  SEQ0163    7.10%    passed     99.90%
 165  SEQ0164    7.69%    passed     90.52%
 166  SEQ0165    6.51%    passed     52.00%
 167  SEQ0166    7.40%    passed     39.16%
 168  SEQ0167    5.62%    passed     82.23%
 169  SEQ0168    6.80%    passed     90.84%
 170  SEQ0169    8.28%    passed     97.07%
 171  SEQ0170    6.80%    passed     98.80%
 172  SEQ0171    7.69%    passed     98.69%
 173  SEQ0172    6.51%    failed      3.15%
 174  SEQ0173    7.10%    passed      9.44%
 175  SEQ0174    6.51%    passed     88.44%
 176  SEQ0175    7.69%    passed     84.85%
 177  SEQ0176    6.21%    passed     25.90%
 178  SEQ0177    7.69%    passed     66.91%
 179  SEQ0178    7.99%    passed     73.93%
 180  SEQ0179    7.69%    passed     70.94%
 181  SEQ0180    7.10%    passed     90.37%
 182  SEQ0181    7.10%    passed     85.59%
 183  SEQ0182    5.03%    failed      2.36%
 184  SEQ0183    6.80%    passed     34.62%
 185  SEQ0184    7.69%    passed     91.96%
 186  SEQ0185    7.40%    passed     62.94%
 187  SEQ0186    8.58%    passed     68.59%
 188  SEQ0187    8.88%    passed     94.92%
 189  SEQ0188    8.28%    passed     83.19%
 190  SEQ0189    9.47%    passed     96.45%
 191  SEQ0190    7.10%    passed     20.07%
 192  SEQ0191    6.21%    failed      0.00%
 193  SEQ0192    8.88%    passed     98.32%
 194  SEQ0193    7.69%    passed     84.23%
 195  SEQ0194    9.76%    passed     91.45%
 196  SEQ0195    8.28%    passed     69.63%
 197  SEQ0196    6.21%    passed     94.83%
 198  SEQ0197   10.65%    passed     60.79%
 199  SEQ0198    7.99%    passed     84.92%
 200  SEQ0199    8.28%    passed     98.22%
 201  SEQ0200    7.99%    passed     95.74%
 202  SEQ0201    7.99%    passed     75.64%
 203  SEQ0202    8.28%    passed     84.86%
 204  SEQ0203    8.58%    passed     84.61%
 205  SEQ0204   25.74%    passed     66.37%
 206  SEQ0205    8.88%    passed     99.15%
 207  SEQ0206   10.95%    passed     13.69%
 208  SEQ0207    8.58%    passed     97.43%
 209  SEQ0208    6.21%    passed     98.59%
 210  SEQ0209    6.51%    passed     81.56%
 211  SEQ0210    7.99%    passed     21.13%
 212  SEQ0211    8.58%    passed     77.56%
 213  SEQ0212    7.69%    passed     82.49%
 214  SEQ0213    7.40%    passed     86.87%
 215  SEQ0214    6.80%    passed     99.86%
 216  SEQ0215    6.80%    passed     70.60%
 217  SEQ0216    8.88%    passed     96.45%
 218  SEQ0217    6.80%    passed     81.00%
 219  SEQ0218    7.69%    passed     86.92%
 220  SEQ0219   10.06%    passed     99.24%
 221  SEQ0220    7.99%    passed     44.35%
 222  SEQ0221    9.17%    passed     78.52%
 223  SEQ0222   10.65%    passed     89.67%
 224  SEQ0223    6.21%    passed     56.32%
 225  SEQ0224   20.12%    passed     79.71%
 226  SEQ0225    7.69%    passed      7.02%
 227  SEQ0226    7.40%    passed     97.15%
 228  SEQ0227    7.69%    passed     89.86%
 229  SEQ0228    8.58%    passed     99.65%
 230  SEQ0229    7.40%    passed     71.98%
 231  SEQ0230    7.99%    passed     91.69%
 232  SEQ0231    9.76%    passed     79.09%
 233  SEQ0232    9.17%    passed     72.53%
 234  SEQ0233    7.69%    passed     38.82%
 235  SEQ0234    8.88%    passed     98.48%
 236  SEQ0235   10.36%    passed     98.65%
 237  SEQ0236    9.17%    passed     23.32%
 238  SEQ0237    7.40%    passed     18.47%
 239  SEQ0238    7.69%    passed     84.16%
 240  SEQ0239    6.21%    passed     89.46%
 241  SEQ0240    7.69%    passed     90.21%
 242  SEQ0241    8.88%    passed     99.74%
 243  SEQ0242    7.40%    passed      7.85%
 244  SEQ0243    8.28%    passed     93.10%
 245  SEQ0244    7.69%    passed     91.70%
 246  SEQ0245    6.21%    passed     61.28%
 247  SEQ0246    8.58%    passed     98.85%
 248  SEQ0247    7.10%    passed     71.01%
 249  SEQ0248    6.21%    passed     90.98%
 250  SEQ0249    5.33%    passed     46.76%
 251  SEQ0250   10.65%    passed     72.36%
 252  SEQ0251    5.33%    passed     93.56%
 253  SEQ0252    6.21%    passed     15.44%
 254  SEQ0253   12.72%    passed     90.93%
 255  SEQ0254    6.80%    passed     72.73%
 256  SEQ0255   19.82%    passed     96.92%
 257  SEQ0256    8.58%    passed     94.17%
 258  SEQ0257    7.40%    passed     77.26%
 259  SEQ0258    7.40%    passed     73.89%
 260  SEQ0259    4.44%    passed     98.28%
 261  SEQ0260    8.28%    passed     84.84%
 262  SEQ0261    7.69%    passed     69.47%
 263  SEQ0262    5.33%    passed      7.74%
 264  SEQ0263    4.14%    passed     72.24%
 265  SEQ0264    7.40%    passed     96.85%
 266  SEQ0265    5.03%    passed     97.16%
 267  SEQ0266   11.24%    passed     57.45%
 268  SEQ0267    7.99%    passed     75.14%
 269  SEQ0268    5.62%    passed     94.97%
 270  SEQ0269    7.10%    failed      1.12%
 271  SEQ0270    7.40%    passed     38.62%
 272  SEQ0271    8.58%    passed     49.21%
 273  SEQ0272    8.28%    passed     82.86%
 274  SEQ0273    7.10%    passed     88.88%
 275  SEQ0274   10.95%    passed     81.75%
 276  SEQ0275    6.51%    passed     93.08%
 277  SEQ0276    6.51%    passed     57.10%
 278  SEQ0277    6.80%    passed     93.03%
 279  SEQ0278    6.80%    passed     91.71%
 280  SEQ0279    9.47%    passed     26.78%
 281  SEQ0280    5.62%    passed     69.79%
 282  SEQ0281    9.76%    passed     99.69%
 283  SEQ0282    7.69%    passed     99.97%
 284  SEQ0283    7.69%    passed     93.38%
 285  SEQ0284    6.80%    passed     32.82%
 286  SEQ0285    7.69%    passed     94.04%
 287  SEQ0286    8.28%    passed     88.66%
 288  SEQ0287    8.58%    passed     99.90%
 289  SEQ0288    8.58%    passed     99.93%
 290  SEQ0289    8.58%    passed     99.97%
 291  SEQ0290    7.10%    passed     91.07%
 292  SEQ0291    8.58%    passed     96.46%
 293  SEQ0292    8.58%    passed     99.97%
 294  SEQ0293    8.58%    passed     99.92%
 295  SEQ0294    8.58%    passed     99.88%
 296  SEQ0295    7.99%    passed     84.54%
 297  SEQ0296    8.58%    passed     98.19%
 298  SEQ0297    6.80%    passed     93.89%
 299  SEQ0298    8.28%    passed     90.81%
 300  SEQ0299    8.58%    passed     97.35%
 301  SEQ0300    8.58%    passed     97.81%
 302  SEQ0301    8.28%    passed     79.59%
 303  SEQ0302    8.58%    passed     99.93%
 304  SEQ0303    7.99%    passed     90.91%
 305  SEQ0304    8.58%    passed     95.88%
 306  SEQ0305    8.28%    passed     99.26%
 307  SEQ0306    8.28%    passed     79.00%
 308  SEQ0307    8.88%    passed     55.29%
 309  SEQ0308    8.58%    passed     99.92%
 310  SEQ0309    8.58%    passed     97.80%
 311  SEQ0310    6.51%    passed     19.75%
 312  SEQ0311    8.58%    passed     99.84%
 313  SEQ0312    7.99%    passed     95.26%
 314  SEQ0313    8.58%    passed     97.59%
 315  SEQ0314    7.99%    passed     87.61%
 316  SEQ0315    8.58%    passed     99.93%
 317  SEQ0316    7.69%    passed     26.26%
 318  SEQ0317    8.88%    passed     60.80%
 319  SEQ0318   11.24%    passed     99.70%
 320  SEQ0319    6.21%    passed     77.33%
 321  SEQ0320    7.10%    passed     83.76%
 322  SEQ0321    7.69%    passed     95.58%
 323  SEQ0322    7.69%    passed     95.95%
 324  SEQ0323    7.69%    passed     95.99%
 325  SEQ0324    7.69%    passed     96.54%
 326  SEQ0325    7.69%    passed     91.36%
 327  SEQ0326    8.58%    passed     97.70%
 328  SEQ0327    7.69%    passed     47.87%
 329  SEQ0328    7.69%    passed     48.52%
 330  SEQ0329    7.69%    passed     58.18%
 331  SEQ0330    7.69%    passed     38.74%
 332  SEQ0331    8.58%    passed     77.29%
 333  SEQ0332    8.28%    passed     46.54%
 334  SEQ0333    8.58%    passed     90.74%
 335  SEQ0334    7.69%    passed     96.68%
 336  SEQ0335    7.69%    passed     28.12%
 337  SEQ0336    4.73%    passed     96.91%
 338  SEQ0337    7.10%    passed     58.68%
 339  SEQ0338    8.28%    passed     64.31%
 340  SEQ0339    7.69%    passed     42.55%
 341  SEQ0340   16.57%    passed     68.24%
 342  SEQ0341    7.99%    passed     88.27%
 343  SEQ0342    7.40%    passed     97.79%
 344  SEQ0343    7.10%    passed     74.53%
 345  SEQ0344    7.69%    passed     86.79%
 346  SEQ0345    7.69%    passed     88.99%
 347  SEQ0346    6.80%    passed     82.44%
 348  SEQ0347    6.80%    failed      1.63%
 349  SEQ0348    7.10%    passed     37.09%
 350  SEQ0349    7.69%    passed     14.01%
 351  SEQ0350    5.92%    passed     57.93%
 352  SEQ0351    7.40%    passed     79.58%
 353  SEQ0352    7.99%    passed     54.04%
 354  SEQ0353    6.51%    passed     44.86%
 355  SEQ0354    9.17%    passed     59.96%
 356  SEQ0355    8.58%    passed     93.05%
 357  SEQ0356    7.10%    passed     75.04%
 358  SEQ0357    7.40%    passed     79.48%
 359  SEQ0358    7.99%    passed     63.21%
 360  SEQ0359    8.58%    passed     71.94%
 361  SEQ0360    8.58%    passed     97.76%
 362  SEQ0361    8.58%    passed     73.22%
 363  SEQ0362    7.69%    passed     71.25%
 364  SEQ0363    7.69%    passed     35.63%
 365  SEQ0364    7.40%    passed     95.00%
 366  SEQ0365    7.99%    passed     95.65%
 367  SEQ0366    6.21%    passed     96.86%
 368  SEQ0367    7.10%    passed     87.12%
 369  SEQ0368   15.09%    passed     97.61%
 370  SEQ0369    5.62%    passed     87.67%
 371  SEQ0370    7.99%    passed     93.23%
 372  SEQ0371    6.80%    passed     76.51%
 373  SEQ0372    7.99%    passed     76.60%
 374  SEQ0373    6.51%    passed     17.04%
 375  SEQ0374    5.62%    passed     91.07%
 376  SEQ0375    7.69%    passed     82.47%
 377  SEQ0376    7.69%    passed      7.83%
 378  SEQ0377    6.21%    passed     58.67%
 379  SEQ0378    7.69%    passed     67.46%
 380  SEQ0379    7.69%    passed     93.41%
 381  SEQ0380   10.95%    passed     97.69%
 382  SEQ0381    7.99%    passed     99.31%
 383  SEQ0382    7.99%    passed     99.72%
 384  SEQ0383    7.99%    passed     89.57%
 385  SEQ0384    8.28%    passed     65.08%
 386  SEQ0385    5.92%    passed     80.48%
 387  SEQ0386    8.28%    passed     92.87%
 388  SEQ0387    8.58%    passed     83.89%
 389  SEQ0388    7.40%    passed     82.07%
 390  SEQ0389    8.28%    passed     91.94%
 391  SEQ0390    7.40%    passed     81.29%
 392  SEQ0391    6.21%    passed     98.01%
 393  SEQ0392    6.21%    passed     95.96%
 394  SEQ0393    6.21%    passed     96.55%
 395  SEQ0394    8.28%    passed     95.71%
 396  SEQ0395    8.28%    passed     97.92%
 397  SEQ0396   10.65%    passed     98.05%
 398  SEQ0397    5.33%    passed     54.45%
 399  SEQ0398    8.58%    passed     96.50%
 400  SEQ0399    8.58%    passed     89.65%
 401  SEQ0400    7.40%    passed     38.77%
 402  SEQ0401    6.80%    passed     59.57%
 403  SEQ0402    6.80%    passed     52.84%
 404  SEQ0403    6.51%    passed     90.70%
 405  SEQ0404    7.40%    passed     84.09%
 406  SEQ0405    5.62%    passed     95.65%
 407  SEQ0406    8.58%    passed     99.90%
 408  SEQ0407    5.92%    passed     19.16%
 409  SEQ0408    7.99%    passed     64.23%
 410  SEQ0409    5.33%    passed     96.33%
 411  SEQ0410    8.88%    passed     69.44%
 412  SEQ0411    6.21%    passed     29.20%
 413  SEQ0412    9.47%    passed     99.87%
 414  SEQ0413    6.51%    passed     78.28%
 415  SEQ0414    7.10%    passed     94.78%
 416  SEQ0415    6.80%    passed     84.80%
 417  SEQ0416    7.10%    passed     62.74%
 418  SEQ0417    8.88%    passed     58.23%
 419  SEQ0418    8.58%    passed     78.71%
 420  SEQ0419    7.99%    passed     64.87%
 421  SEQ0420    7.40%    passed     93.15%
 422  SEQ0421   22.78%    failed      1.58%
 423  SEQ0422    8.28%    passed     99.36%
 424  SEQ0423    8.28%    passed     74.16%
 425  SEQ0424   11.54%    passed     94.46%
 426  SEQ0425    7.69%    passed     72.00%
 427  SEQ0426    6.80%    passed     46.81%
 428  SEQ0427    6.80%    passed     21.46%

In [35]:
# fasttree

!fasttree ../processed/m2or_sequences_phylogeny_msa_gt01.fasta > ../processed/m2or_sequences_phylogeny_msa_gt01_fasttree.nw

FastTree Version 2.1.11 Double precision (No SSE3)
Alignment: ../processed/m2or_sequences_phylogeny_msa_gt01.fasta
Amino acid distances: BLOSUM45 Joins: balanced Support: SH-like 1000
Search: Normal +NNI +SPR (2 rounds range 10) +ML-NNI opt-each=1
TopHits: 1.00*sqrtN close=default refresh=0.80
ML Model: Jones-Taylor-Thorton, CAT approximation with 20 rate categories
Initial topology in 0.77 seconds0 of   1378
Refining topology: 42 rounds ME-NNIs, 2 rounds ME-SPRs, 21 rounds ML-NNIs
Total branch-length 119.440 after 3.38 sec 1201 of 1379 splits, 0 changes   ax delta 0.035)
ML-NNI round 1: LogLk = -205633.278 NNIs 289 max delta 12.87 Time 9.79nges (max delta 12.873)
Switched to using 20 rate categories (CAT approximation)20 of 20
Rate categories were divided by 1.201 so that average rate = 1.0
CAT-based log-likelihoods may not be comparable across runs
Use -gamma for approximate but comparable Gamma(20) log-likelihoods
ML-NNI round 2: LogLk = -195052.989 NNIs 229 max delta 6.53 Time 16.09nges (max delta 6.530)
ML-NNI round 3: LogLk = -195013.118 NNIs 128 max delta 5.12 Time 18.29ges (max delta 4.670)
ML-NNI round 4: LogLk = -195000.656 NNIs 81 max delta 1.16 Time 19.58ges (max delta 1.157)
ML-NNI round 5: LogLk = -194997.455 NNIs 47 max delta 2.74 Time 20.23ges (max delta 2.736)
ML-NNI round 6: LogLk = -194997.266 NNIs 29 max delta 0.04 Time 20.61ges (max delta 0.039)
Turning off heuristics for final round of ML NNIs (converged)
ML-NNI round 7: LogLk = -194911.189 NNIs 137 max delta 2.83 Time 26.07 (final)x delta 2.827)
Optimize all lengths: LogLk = -194908.803 Time 27.49
Total time: 31.80 seconds Unique: 1381/1399 Bad splits: 0/1378al splits

In [1]:
from ete4 import PhyloTree

t = PhyloTree("../processed/m2or_sequences_phylogeny_msa_gt01_fasttree.nw")
midp = t.get_midpoint_outgroup()
t.set_outgroup(midp)

children = list(t.children)
child1, child2 = children[0], children[1]

headers_child1 = [leaf.name for leaf in child1.leaves()]
headers_child2 = [leaf.name for leaf in child2.leaves()]

with open("../processed/child1_headers.txt", "w") as f:
    for h in headers_child1:
        f.write(h + "\n")
with open("../processed/child2_headers.txt", "w") as f:
    for h in headers_child2:
        f.write(h + "\n")

t.explore()

Creating new server.
Explorer available at http://127.0.0.1:5000

In [16]:
with open("../processed/child1_headers.txt") as f:
    child1_set = set(line.strip() for line in f if line.strip())
with open("../processed/child2_headers.txt") as f:
    child2_set = set(line.strip() for line in f if line.strip())

def get_class(seq_id):
    if seq_id in child1_set:
        return "class 1"
    elif seq_id in child2_set:
        return "class 2"
    else:
        return "other"  

pairs["Class"] = pairs["seq_id"].apply(get_class)

In [17]:
pairs

,Species,UniProt ID,Sequence,SMILES,Mixture,Responsive,seq_id,smiles_id,mutation,Class
0,homo sapiens,Q8NGN2,MTSRSVCEKMTMTTENPNQTVVSHFFLEGLRYTAKHSSLFFLLFLL...,CC1=CC[C@H](CC1)C(=C)C,mono,0,SEQ0000,SML0000,False,class 2
1,homo sapiens,Q8NGN2,MTSRSVCEKMTMTTENPNQTVVSHFFLEGLRYTAKHSSLFFLLFLL...,CC1=CC[C@@H](CC1=O)C(=C)C,mono,0,SEQ0000,SML0001,False,class 2
2,homo sapiens,Q8NGN2,MTSRSVCEKMTMTTENPNQTVVSHFFLEGLRYTAKHSSLFFLLFLL...,C[C@H]1CC[C@@H]([C@H](C1)O)C(C)C,mono,0,SEQ0000,SML0002,False,class 2
3,homo sapiens,Q8NGN2,MTSRSVCEKMTMTTENPNQTVVSHFFLEGLRYTAKHSSLFFLLFLL...,CCCCO,mono,0,SEQ0000,SML0003,False,class 2
4,homo sapiens,Q8NGN2,MTSRSVCEKMTMTTENPNQTVVSHFFLEGLRYTAKHSSLFFLLFLL...,CCCCOCC(C)O,sum of isomers,0,SEQ0000,SML0004,False,class 2
...,...,...,...,...,...,...,...,...,...,...
53439,homo sapiens,A6NGY5,MLQNQDTMEILSNSTSKFPTFLLTGIPGLESAHVWISIPFCCFYAI...,CCCCCC=O,mono,0,SEQ0523,SML0163,False,class 1
53440,homo sapiens,Q8NGJ9,MAIFNNTTSSSSNFLLTAFPGLECAHVWISIPVCCLYTIALLGNSM...,CCCCCC=O,mono,0,SEQ0952,SML0163,False,class 1
53441,homo sapiens,Q8NH55,MLHTNNTQFHPSTFLVVGVPGLEDVHVWIGFPFFAVYLTALLGNII...,CCCCCC=O,mono,0,SEQ0955,SML0163,False,class 1
53442,homo sapiens,Q8NGH7,MTLVSFFSFLSKPLIMLLSNSSWRLSQPSFLLVGIPGLEESQHWIA...,CCCCCC=O,mono,0,SEQ0957,SML0163,False,class 1
53443,homo sapiens,Q8NGH8,MASPSNDSTAPVSEFLLICFPNFQSWQHWLSLPLSLLFLLAMGANT...,CCCCCC=O,mono,0,SEQ0506,SML0163,False,class 1

In [18]:
print("unique sequencess:", pairs["Sequence"].nunique())
print("unique SMILES:", pairs["SMILES"].nunique())
print("Counts:", pairs["Responsive"].value_counts())
print("Mutated sequences:", pairs[pairs["mutation"] == True]["Sequence"].nunique())
print("Wild-type sequences:", pairs[pairs["mutation"] == False]["Sequence"].nunique())
print("Class 1 sequences:", pairs[pairs["Class"] == "class 1"]["Sequence"].nunique())
print("Class 2 sequences:", pairs[pairs["Class"] == "class 2"]["Sequence"].nunique())

inactive_sequences = pairs.groupby("Sequence")["Responsive"].sum().loc[lambda s: s == 0].index.tolist()
print("inactive sequences:", len(inactive_sequences))

unique sequencess: 1399
unique SMILES: 754
Counts: Responsive
0    49109
1     3066
Name: count, dtype: int64
Mutated sequences: 810
Wild-type sequences: 589
Class 1 sequences: 197
Class 2 sequences: 1202
inactive sequences: 694

In [40]:
# save the original dataset
pairs.to_csv("../processed/m2or_pairs_model.csv", index=False)